Repository Automattic/notifications-panel, pull requests merged in 2018-03, with the labels that each got.

#236 Replace the current spinner with Calypso's new pure CSS spinner.
  src/boot/stylesheets/actions.scss
  src/boot/stylesheets/spinner.scss
  src/templates/comment-reply-input.jsx
  src/templates/note-list.jsx
  src/templates/spinner.jsx
Labels: [Status] needs-review

#222 Actions: add Edit comment and reorder the icons
  .editorconfig
  src/helpers/input.js
  src/helpers/notes.js
  src/state/action-types.js
  src/state/ui/actions.js
  src/templates/actions.jsx
  src/templates/button-edit.jsx
  src/templates/gridicons.jsx
  standalone/index.js
Labels: [Status] ready-to-merge

#240 Edit Comment: Remove title tag from pencil Gridicon
  src/templates/gridicons.jsx
Labels: [Status] ready-to-merge, [Type] Bug
